### ISSUE TITLE
also add unzipped addon files?

### ISSUE THREAD

**Issue by ayy-star** [SaplingDevs/Sapling#1]
Instead of keeping only the zip file of the addon in the repository, you should also include all the source files of the addon so that other people might be able to contribute to this project easily. If someone were to mak a pull request to this repo as it is now, it would not be very convinient to make it or for you to review it.

**Comment by AlecsDeveloper** [comment]
Totally agree, I'll come back to it later.

**Comment by AlecsDeveloper** [comment]
the files have been updated! sorry for the delay 😅
